### ISSUE TITLE
benchmark results in GFlops

### ISSUE THREAD

**Issue by paklui** [eth-cscs/SpFFT#17]
Hello, would it be possible to report the benchmark results in GFlops? Thanks.

**Comment by AdhocMan** [comment]
The actual computations are done by external libraries like FFTW, cuFFT or rocFFT.
Depending on the size, different algorithms may be used internally by these libraries and therefore the number of operations may be different as well. Since there is no way to query each library for the number of operations, one would have to use some kind of estimate.
For example, FFTW uses some fixed formula for benchmarking:  [http://www.fftw.org/speed/method.html](http://www.fftw.org/speed/method.html)
This approach is essentially just a scaling of time measurements without accurately representing the true number of Flops, so I'm reluctant to use something like this.

**Comment by paklui** [comment]
Thank you for your response
